<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Capítulo 5 – Series de Tiempo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./cap4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./cap5.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capítulo 5</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Series de Tiempo</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./box_jenk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Enfoque de Box-Jenkins</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Capítulo 4</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capítulo 5</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#analysis-of-u.s.-gnp" id="toc-analysis-of-u.s.-gnp" class="nav-link active" data-scroll-target="#analysis-of-u.s.-gnp"><span class="header-section-number">3.1</span> Analysis of U.S. GNP</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">3.1.1</span> Background</a></li>
  </ul></li>
  <li><a href="#arch-analysis-of-the-djia-returns" id="toc-arch-analysis-of-the-djia-returns" class="nav-link" data-scroll-target="#arch-analysis-of-the-djia-returns"><span class="header-section-number">3.2</span> ARCH Analysis of the DJIA Returns</a>
  <ul class="collapse">
  <li><a href="#background-1" id="toc-background-1" class="nav-link" data-scroll-target="#background-1"><span class="header-section-number">3.2.1</span> Background</a></li>
  </ul></li>
  <li><a href="#aparch-analysis-of-the-djia-returns" id="toc-aparch-analysis-of-the-djia-returns" class="nav-link" data-scroll-target="#aparch-analysis-of-the-djia-returns"><span class="header-section-number">3.3</span> APARCH Analysis of the DJIA Returns</a>
  <ul class="collapse">
  <li><a href="#background-2" id="toc-background-2" class="nav-link" data-scroll-target="#background-2"><span class="header-section-number">3.3.1</span> Background</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capítulo 5</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="analysis-of-u.s.-gnp" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="analysis-of-u.s.-gnp"><span class="header-section-number">3.1</span> Analysis of U.S. GNP</h2>
<section id="background" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="background"><span class="header-section-number">3.1.1</span> Background</h3>
<p>In Example 3.39, we fit an MA(2) model and an AR(1) model to the U.S. GNP series. The residuals from both models appeared to resemble a white noise process, but Example 3.43 suggested that the AR(1) model might be a better fit. It has been proposed that the U.S. GNP series may exhibit ARCH (Autoregressive Conditional Heteroskedasticity) errors, so we will investigate this possibility in this example.</p>
<p>If the GNP noise term follows an ARCH process, the squared residuals from the model should behave like a non-Gaussian AR(1) process, as noted in Equation 5.39.</p>
<section id="initial-analysis-of-residuals" class="level4" data-number="3.1.1.1">
<h4 data-number="3.1.1.1" class="anchored" data-anchor-id="initial-analysis-of-residuals"><span class="header-section-number">3.1.1.1</span> Initial Analysis of Residuals</h4>
<p>The following R code generates the ACF and PACF plots of the squared residuals to check for remaining dependence:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(astsa)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit AR(1) model to differenced log-transformed GNP</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">sarima</span>(<span class="fu">diff</span>(<span class="fu">log</span>(gnp)), <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>initial  value -4.589567 
iter   2 value -4.654150
iter   3 value -4.654150
iter   4 value -4.654151
iter   4 value -4.654151
iter   4 value -4.654151
final  value -4.654151 
converged
initial  value -4.655919 
iter   2 value -4.655921
iter   3 value -4.655922
iter   4 value -4.655922
iter   5 value -4.655922
iter   5 value -4.655922
iter   5 value -4.655922
final  value -4.655922 
converged
&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;
 
Coefficients: 
      Estimate     SE t.value p.value
ar1     0.3467 0.0627  5.5255       0
xmean   0.0083 0.0010  8.5398       0

sigma^2 estimated as 9.029569e-05 on 220 degrees of freedom 
 
AIC = -6.44694  AICc = -6.446693  BIC = -6.400958 
 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap5_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf2</span>(<span class="fu">resid</span>(u<span class="sc">$</span>fit)<span class="sc">^</span><span class="dv">2</span>, <span class="dv">20</span>)  <span class="co"># ACF and PACF of squared residuals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap5_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4]  [,5] [,6]  [,7] [,8] [,9] [,10] [,11] [,12] [,13]
ACF  0.12 0.13 0.03 0.13  0.01 0.05 -0.03 0.06 0.08 -0.08  0.09  0.10  0.01
PACF 0.12 0.12 0.00 0.12 -0.02 0.02 -0.04 0.05 0.08 -0.12  0.11  0.09 -0.05
     [,14] [,15] [,16] [,17] [,18] [,19] [,20]
ACF   0.04  0.15 -0.02  0.04 -0.05  0.01  0.05
PACF  0.05  0.13 -0.09  0.01 -0.05  0.00  0.04</code></pre>
</div>
</div>
<p>The plots reveal that there may be some small remaining dependence in the squared residuals.</p>
</section>
<section id="fitting-an-ar1-arch1-model" class="level4" data-number="3.1.1.2">
<h4 data-number="3.1.1.2" class="anchored" data-anchor-id="fitting-an-ar1-arch1-model"><span class="header-section-number">3.1.1.2</span> Fitting an AR(1)-ARCH(1) Model</h4>
<p>To examine the ARCH nature of the residuals, we fit an AR(1)-ARCH(1) model to the GNP returns using the <code>fGarch</code> package. The <code>garchFit</code> function models the AR(1) and ARCH(1) components. The code and a summary of the results are shown below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fGarch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: Packages 'fBasics', 'timeDate', and 'timeSeries' are no longer
attached to the search() path when 'fGarch' is attached.

If needed attach them yourself in your R script by e.g.,
        require("timeSeries")</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit AR(1)-ARCH(1) model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span> <span class="fu">arma</span>(<span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">garch</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">data =</span> <span class="fu">diff</span>(<span class="fu">log</span>(gnp)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Series Initialization:
 ARMA Model:                arma
 Formula Mean:              ~ arma(1, 0)
 GARCH Model:               garch
 Formula Variance:          ~ garch(1, 0)
 ARMA Order:                1 0
 Max ARMA Order:            1
 GARCH Order:               1 0
 Max GARCH Order:           1
 Maximum Order:             1
 Conditional Dist:          norm
 h.start:                   2
 llh.start:                 1
 Length of Series:          222
 Recursion Init:            mci
 Series Scale:              0.01015924

Parameter Initialization:
 Initial Parameters:          $params
 Limits of Transformations:   $U, $V
 Which Parameters are Fixed?  $includes
 Parameter Matrix:
                     U          V    params includes
    mu     -8.20681904   8.206819 0.8205354     TRUE
    ar1    -0.99999999   1.000000 0.3466459     TRUE
    omega   0.00000100 100.000000 0.1000000     TRUE
    alpha1  0.00000001   1.000000 0.1000000     TRUE
    gamma1 -0.99999999   1.000000 0.1000000    FALSE
    delta   0.00000000   2.000000 2.0000000    FALSE
    skew    0.10000000  10.000000 1.0000000    FALSE
    shape   1.00000000  10.000000 4.0000000    FALSE
 Index List of Parameters to be Optimized:
    mu    ar1  omega alpha1 
     1      2      3      4 
 Persistence:                  0.1 


--- START OF TRACE ---
Selected Algorithm: nlminb 

R coded nlminb Solver: 

  0:     682.89527: 0.820535 0.346646 0.100000 0.100000
  1:     308.43148: 0.763492 0.258112  1.06104 0.352453
  2:     306.07332: 0.681276 0.195897  1.04763 0.304072
  3:     301.00807: 0.561958 0.448458 0.825277 0.0402737
  4:     298.88361: 0.383716 0.465477 0.632947 0.385969
  5:     296.74288: 0.504144 0.389445 0.683635 0.247795
  6:     296.67703: 0.497724 0.366843 0.688130 0.229496
  7:     296.60039: 0.500011 0.385702 0.703145 0.211105
  8:     296.59692: 0.515646 0.374174 0.690079 0.194961
  9:     296.56381: 0.513570 0.367018 0.702272 0.200013
 10:     296.55723: 0.523440 0.363126 0.708406 0.194151
 11:     296.55632: 0.522578 0.364913 0.710104 0.194839
 12:     296.55598: 0.520871 0.364956 0.710924 0.193212
 13:     296.55568: 0.519486 0.366571 0.710212 0.194511
 14:     296.55568: 0.519509 0.366597 0.710266 0.194512
 15:     296.55568: 0.519511 0.366585 0.710290 0.194451
 16:     296.55568: 0.519505 0.366562 0.710299 0.194464
 17:     296.55568: 0.519526 0.366560 0.710295 0.194472
 18:     296.55568: 0.519522 0.366563 0.710295 0.194471

Final Estimate of the Negative LLH:
 LLH:  -722.2849    norm LLH:  -3.253536 
          mu          ar1        omega       alpha1 
0.0052779470 0.3665625656 0.0000733096 0.1944713341 

R-optimhess Difference Approximated Hessian Matrix:
                 mu           ar1         omega        alpha1
mu     -2749495.418 -24170.124984  4.546826e+06 -1.586692e+03
ar1      -24170.125   -390.266822  1.253879e+04 -6.733789e+00
omega   4546825.784  12538.791045 -1.590043e+10 -7.069342e+05
alpha1    -1586.692     -6.733789 -7.069342e+05 -1.425395e+02
attr(,"time")
Time difference of 0.004781961 secs

--- END OF TRACE ---


Time to Estimate Parameters:
 Time difference of 0.03493953 secs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~arma(1, 0) + garch(1, 0), data = diff(log(gnp))) 

Mean and Variance Equation:
 data ~ arma(1, 0) + garch(1, 0)
&lt;environment: 0x55e07c189ca8&gt;
 [data = diff(log(gnp))]

Conditional Distribution:
 norm 

Coefficient(s):
        mu         ar1       omega      alpha1  
0.00527795  0.36656257  0.00007331  0.19447133  

Std. Errors:
 based on Hessian 

Error Analysis:
        Estimate  Std. Error  t value Pr(&gt;|t|)    
mu     5.278e-03   8.996e-04    5.867 4.44e-09 ***
ar1    3.666e-01   7.514e-02    4.878 1.07e-06 ***
omega  7.331e-05   9.011e-06    8.135 4.44e-16 ***
alpha1 1.945e-01   9.554e-02    2.035   0.0418 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 722.2849    normalized:  3.253536 

Description:
 Mon Nov 18 14:09:35 2024 by user:  


Standardised Residuals Tests:
                                 Statistic     p-Value
 Jarque-Bera Test   R    Chi^2   9.1180362 0.010472337
 Shapiro-Wilk Test  R    W       0.9842406 0.014336495
 Ljung-Box Test     R    Q(10)   9.8743260 0.451587525
 Ljung-Box Test     R    Q(15)  17.5585456 0.286584404
 Ljung-Box Test     R    Q(20)  23.4136291 0.268943681
 Ljung-Box Test     R^2  Q(10)  19.2821015 0.036822455
 Ljung-Box Test     R^2  Q(15)  33.2364834 0.004352735
 Ljung-Box Test     R^2  Q(20)  37.7425917 0.009518989
 LM Arch Test       R    TR^2   25.4162474 0.012969006

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-6.471035 -6.409726 -6.471669 -6.446282 </code></pre>
</div>
</div>
<p>The estimates for the AR(1) component are ( = 0.005 ) (mu) and ( = 0.367 ) (ar1). The ARCH(1) parameters are ( _0 = 0 ) (omega) and ( _1 = 0.194 ), which is significant with a p-value around 0.02.</p>
</section>
<section id="residual-diagnostics" class="level4" data-number="3.1.1.3">
<h4 data-number="3.1.1.3" class="anchored" data-anchor-id="residual-diagnostics"><span class="header-section-number">3.1.1.3</span> Residual Diagnostics</h4>
<p>Various tests were performed on the residuals and squared residuals. Notable results include:</p>
<ul>
<li><strong>Jarque-Bera Test</strong>: Chi-squared statistic of 9.118 (p-value = 0.010), suggesting some non-normal skewness and kurtosis in the residuals.</li>
<li><strong>Shapiro-Wilk Test</strong>: W statistic of 0.984 (p-value = 0.014), indicating deviation from normality based on empirical order statistics.</li>
<li><strong>Ljung-Box Tests</strong>:
<ul>
<li><strong>Residuals [R]</strong>: Q(20) statistic of 23.414 (p-value = 0.269), suggesting no significant autocorrelation in residuals.</li>
<li><strong>Squared Residuals [R^2]</strong>: Q(20) statistic of 37.743 (p-value = 0.010), indicating some dependence in squared residuals.</li>
</ul></li>
</ul>
<p>The diagnostics imply that the ARCH(1) model captures the non-constant variance pattern, with significant ARCH effects in the U.S. GNP series.</p>
</section>
</section>
</section>
<section id="arch-analysis-of-the-djia-returns" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="arch-analysis-of-the-djia-returns"><span class="header-section-number">3.2</span> ARCH Analysis of the DJIA Returns</h2>
<section id="background-1" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="background-1"><span class="header-section-number">3.2.1</span> Background</h3>
<p>The daily returns of the Dow Jones Industrial Average (DJIA) exhibit classic GARCH characteristics, including volatility clustering. Additionally, there is a low level of autocorrelation in the series itself. To capture both of these features, we fit an AR(1)-GARCH(1, 1) model to the series, assuming <strong>t-distributed errors</strong> for robustness in handling heavy tails.</p>
<section id="data-preparation-and-initial-analysis" class="level4" data-number="3.2.1.1">
<h4 data-number="3.2.1.1" class="anchored" data-anchor-id="data-preparation-and-initial-analysis"><span class="header-section-number">3.2.1.1</span> Data Preparation and Initial Analysis</h4>
<p>The DJIA returns are computed as the daily log differences of closing prices. The ACF of the returns and squared returns reveal some autocorrelation in the returns and significant autocorrelation in the squared returns, suggesting the presence of GARCH effects. The initial analysis and autocorrelation functions can be plotted with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(astsa)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate daily returns</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>djiar <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">log</span>(djia<span class="sc">$</span>Close))[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Autocorrelation analysis</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">acf2</span>(djiar)     <span class="co"># Shows slight autocorrelation in returns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap5_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]  [,2] [,3]  [,4]  [,5] [,6]  [,7] [,8]  [,9] [,10] [,11] [,12] [,13]
ACF  -0.1 -0.06 0.05 -0.02 -0.06 0.01 -0.02 0.02 -0.01  0.04 -0.01  0.04  0.01
PACF -0.1 -0.07 0.04 -0.02 -0.06 0.00 -0.02 0.03 -0.01  0.04 -0.01  0.04  0.02
     [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
ACF  -0.04 -0.06  0.06  0.00 -0.07  0.02  0.05 -0.06  0.04  0.01 -0.01     0
PACF -0.04 -0.06  0.04  0.02 -0.06  0.00  0.04 -0.04  0.03  0.00  0.00     0
     [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
ACF      0  0.03 -0.03  0.01  0.02 -0.02  0.01  0.01 -0.09  0.03  0.03 -0.02
PACF     0  0.04 -0.03  0.00  0.02  0.00  0.00  0.01 -0.07  0.01  0.02  0.01
     [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
ACF      0  0.03  0.02  0.01  0.00 -0.06     0     0 -0.01  0.02  0.00 -0.04
PACF     0  0.01  0.04  0.02  0.01 -0.06     0     0 -0.01  0.01 -0.01 -0.05
     [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61]
ACF  -0.04 -0.02  0.03  0.00  0.00  0.01 -0.03  0.02  0.02 -0.07  0.02  0.02
PACF -0.04 -0.03  0.01  0.01  0.02  0.01 -0.03  0.01  0.02 -0.05  0.01  0.02</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf2</span>(djiar<span class="sc">^</span><span class="dv">2</span>)   <span class="co"># Shows strong autocorrelation in squared returns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap5_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
ACF   0.2 0.41 0.19 0.31 0.34 0.31 0.32 0.22 0.32  0.24  0.43  0.28  0.25  0.13
PACF  0.2 0.39 0.08 0.15 0.25 0.13 0.11 0.01 0.11  0.05  0.23  0.08 -0.07 -0.16
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
ACF   0.22  0.26  0.27  0.27  0.17  0.23  0.25  0.19  0.29  0.15  0.18  0.15
PACF -0.03  0.04  0.03  0.05 -0.01  0.00  0.09 -0.09  0.07 -0.01  0.00  0.00
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
ACF   0.28  0.22  0.22  0.14  0.16  0.20  0.14  0.25  0.10  0.17  0.12  0.16
PACF  0.12  0.02 -0.03 -0.06  0.00  0.01 -0.06  0.06 -0.03 -0.05  0.02 -0.06
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
ACF   0.15  0.10  0.08  0.08  0.11  0.13  0.13  0.08  0.09  0.11  0.07  0.08
PACF -0.06 -0.06 -0.03  0.01  0.00  0.03  0.02 -0.01  0.00  0.06 -0.02 -0.05
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61]
ACF   0.07  0.08  0.06  0.09  0.06  0.12  0.09  0.06  0.08  0.04  0.08
PACF  0.03  0.04  0.02 -0.02 -0.09  0.08  0.06  0.00  0.01 -0.02  0.00</code></pre>
</div>
</div>
</section>
<section id="fitting-an-ar1-garch11-model" class="level4" data-number="3.2.1.2">
<h4 data-number="3.2.1.2" class="anchored" data-anchor-id="fitting-an-ar1-garch11-model"><span class="header-section-number">3.2.1.2</span> Fitting an AR(1)-GARCH(1,1) Model</h4>
<p>The <code>fGarch</code> package in R allows for fitting an AR(1)-GARCH(1, 1) model with <strong>t-distributed errors</strong> to account for potential heavy tails in the DJIA returns. The following code fits the model and provides a summary of the estimates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fGarch)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit AR(1)-GARCH(1,1) model with t-distributed errors</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>djia.g <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span> <span class="fu">arma</span>(<span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">garch</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">data =</span> djiar, <span class="at">cond.dist =</span> <span class="st">"std"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Series Initialization:
 ARMA Model:                arma
 Formula Mean:              ~ arma(1, 0)
 GARCH Model:               garch
 Formula Variance:          ~ garch(1, 1)
 ARMA Order:                1 0
 Max ARMA Order:            1
 GARCH Order:               1 1
 Max GARCH Order:           1
 Maximum Order:             1
 Conditional Dist:          std
 h.start:                   2
 llh.start:                 1
 Length of Series:          2517
 Recursion Init:            mci
 Series Scale:              0.01210097

Parameter Initialization:
 Initial Parameters:          $params
 Limits of Transformations:   $U, $V
 Which Parameters are Fixed?  $includes
 Parameter Matrix:
                     U           V      params includes
    mu     -0.15336279   0.1533628  0.01533395     TRUE
    ar1    -0.99999999   1.0000000 -0.10129752     TRUE
    omega   0.00000100 100.0000000  0.10000000     TRUE
    alpha1  0.00000001   1.0000000  0.10000000     TRUE
    gamma1 -0.99999999   1.0000000  0.10000000    FALSE
    beta1   0.00000001   1.0000000  0.80000000     TRUE
    delta   0.00000000   2.0000000  2.00000000    FALSE
    skew    0.10000000  10.0000000  1.00000000    FALSE
    shape   1.00000000  10.0000000  4.00000000     TRUE
 Index List of Parameters to be Optimized:
    mu    ar1  omega alpha1  beta1  shape 
     1      2      3      4      6      9 
 Persistence:                  0.9 


--- START OF TRACE ---
Selected Algorithm: nlminb 

R coded nlminb Solver: 

  0:     2966.5649: 0.0153339 -0.101298 0.100000 0.100000 0.800000  4.00000
  1:     2944.7772: 0.0153351 -0.0991717 0.0803850 0.105688 0.794226  3.99986
  2:     2910.9438: 0.0153425 -0.0864389 0.0198837 0.162520 0.809278  4.00053
  3:     2891.9985: 0.0153434 -0.0855696 0.0349997 0.168391 0.817707  4.00077
  4:     2882.6364: 0.0153798 -0.0489475 0.0211398 0.164588 0.840541  4.00286
  5:     2881.9301: 0.0153823 -0.0484838 0.0204238 0.166791 0.845394  4.00314
  6:     2881.5679: 0.0153882 -0.0491671 0.0164038 0.164251 0.847793  4.00365
  7:     2880.9558: 0.0153959 -0.0493820 0.0174436 0.161528 0.852261  4.00434
  8:     2880.6291: 0.0154049 -0.0492037 0.0154767 0.158055 0.855764  4.00516
  9:     2880.3565: 0.0154166 -0.0487266 0.0159444 0.154678 0.859712  4.00626
 10:     2880.1243: 0.0154339 -0.0478609 0.0146355 0.150737 0.862389  4.00794
 11:     2879.9530: 0.0154638 -0.0476576 0.0149075 0.147959 0.865388  4.01087
 12:     2879.8201: 0.0155048 -0.0483157 0.0138749 0.146453 0.866639  4.01497
 13:     2879.7180: 0.0155488 -0.0477882 0.0141937 0.145774 0.867564  4.01936
 14:     2879.4141: 0.0157808 -0.0423403 0.0141381 0.141896 0.868277  4.04243
 15:     2878.3878: 0.0174980 -0.0569546 0.00848860 0.140360 0.874674  4.21079
 16:     2878.2927: 0.0193492 -0.0502757 0.0142265 0.160178 0.862535  4.37200
 17:     2876.3368: 0.0203874 -0.0461078 0.0117835 0.167862 0.852926  4.44641
 18:     2874.7342: 0.0206459 -0.0555791 0.0130825 0.138689 0.869340  4.42804
 19:     2874.6724: 0.0206462 -0.0554532 0.0123098 0.138461 0.869109  4.42806
 20:     2874.6548: 0.0206553 -0.0553211 0.0125311 0.138489 0.869292  4.42857
 21:     2874.6394: 0.0206635 -0.0550129 0.0122399 0.138334 0.869389  4.42904
 22:     2874.6234: 0.0206727 -0.0548830 0.0124501 0.138349 0.869554  4.42956
 23:     2874.6091: 0.0206813 -0.0546059 0.0121936 0.138189 0.869619  4.43005
 24:     2874.5943: 0.0206905 -0.0544775 0.0123915 0.138195 0.869769  4.43057
 25:     2874.5807: 0.0206992 -0.0542217 0.0121569 0.138035 0.869816  4.43107
 26:     2874.5667: 0.0207085 -0.0540958 0.0123467 0.138034 0.869956  4.43160
 27:     2874.5537: 0.0207174 -0.0538569 0.0121278 0.137877 0.869991  4.43211
 28:     2874.5403: 0.0207267 -0.0537340 0.0123108 0.137872 0.870123  4.43264
 29:     2874.5278: 0.0207356 -0.0535096 0.0121041 0.137717 0.870149  4.43315
 30:     2874.5149: 0.0207450 -0.0533899 0.0122810 0.137709 0.870275  4.43368
 31:     2874.5028: 0.0207540 -0.0531784 0.0120844 0.137558 0.870296  4.43419
 32:     2874.4904: 0.0207635 -0.0530620 0.0122555 0.137548 0.870416  4.43473
 33:     2874.4787: 0.0207726 -0.0528620 0.0120673 0.137401 0.870433  4.43525
 34:     2874.4667: 0.0207820 -0.0527489 0.0122328 0.137390 0.870549  4.43578
 35:     2874.4553: 0.0207912 -0.0525594 0.0120521 0.137247 0.870562  4.43630
 36:     2874.4437: 0.0208007 -0.0524496 0.0122124 0.137235 0.870674  4.43684
 37:     2874.4326: 0.0208099 -0.0522698 0.0120383 0.137096 0.870686  4.43736
 38:     2874.4213: 0.0208194 -0.0521631 0.0121935 0.137083 0.870794  4.43789
 39:     2874.4105: 0.0208287 -0.0519922 0.0120255 0.136949 0.870804  4.43842
 40:     2874.3995: 0.0208383 -0.0518887 0.0121759 0.136934 0.870909  4.43895
 41:     2874.3889: 0.0208476 -0.0517261 0.0120134 0.136805 0.870917  4.43948
 42:     2874.3782: 0.0208572 -0.0516257 0.0121593 0.136790 0.871020  4.44002
 43:     2874.3679: 0.0208666 -0.0514707 0.0120019 0.136664 0.871027  4.44055
 44:     2874.3574: 0.0208762 -0.0513733 0.0121435 0.136649 0.871126  4.44108
 45:     2874.3474: 0.0208856 -0.0512255 0.0119909 0.136527 0.871132  4.44161
 46:     2874.3371: 0.0208952 -0.0511310 0.0121283 0.136511 0.871229  4.44215
 47:     2874.3273: 0.0209047 -0.0509898 0.0119802 0.136393 0.871235  4.44268
 48:     2874.3172: 0.0209144 -0.0508982 0.0121136 0.136378 0.871329  4.44321
 49:     2874.3076: 0.0209239 -0.0507633 0.0119698 0.136263 0.871333  4.44374
 50:     2874.2977: 0.0209336 -0.0506745 0.0120995 0.136247 0.871425  4.44428
 51:     2874.2883: 0.0209431 -0.0505454 0.0119597 0.136136 0.871429  4.44481
 52:     2874.2786: 0.0209528 -0.0504593 0.0120858 0.136120 0.871519  4.44535
 53:     2874.2693: 0.0209624 -0.0503357 0.0119499 0.136012 0.871522  4.44588
 54:     2874.2598: 0.0209721 -0.0502524 0.0120725 0.135996 0.871609  4.44641
 55:     2874.2507: 0.0209817 -0.0501339 0.0119403 0.135891 0.871612  4.44694
 56:     2874.2414: 0.0209915 -0.0500532 0.0120596 0.135875 0.871697  4.44748
 57:     2874.2324: 0.0210011 -0.0499396 0.0119308 0.135773 0.871700  4.44801
 58:     2867.2502: 0.0374784 -0.0465701 0.0140411 0.146417 0.849465  5.34102
 59:     2865.2784: 0.0416151 -0.0568642 0.0115908 0.133741 0.863377  5.47854
 60:     2864.2803: 0.0508382 -0.0551564 0.0133502 0.137240 0.863921  5.39588
 61:     2861.7759: 0.0711833 -0.0514599 0.0116358 0.126101 0.868871  5.59207
 62:     2861.6890: 0.0720867 -0.0568481 0.0103059 0.127155 0.870034  5.77185
 63:     2861.6323: 0.0712594 -0.0580540 0.0105727 0.123206 0.871658  5.89046
 64:     2861.6059: 0.0710100 -0.0558795 0.0112294 0.125022 0.869481  5.92682
 65:     2861.6004: 0.0709184 -0.0550834 0.0110167 0.124375 0.870072  5.96212
 66:     2861.6000: 0.0709561 -0.0553609 0.0109915 0.124443 0.870018  5.97670
 67:     2861.6000: 0.0709474 -0.0553160 0.0109949 0.124443 0.870016  5.97866
 68:     2861.6000: 0.0709478 -0.0553153 0.0109957 0.124445 0.870013  5.97877

Final Estimate of the Negative LLH:
 LLH:  -8249.619    norm LLH:  -3.27756 
           mu           ar1         omega        alpha1         beta1 
 8.585376e-04 -5.531526e-02  1.610146e-06  1.244449e-01  8.700127e-01 
        shape 
 5.978770e+00 

R-optimhess Difference Approximated Hessian Matrix:
                  mu           ar1         omega        alpha1         beta1
mu     -4.791651e+07 -4.661861e+04 -1.205634e+09 -3.466862e+04 -9.149105e+04
ar1    -4.661861e+04 -2.490882e+03 -1.234074e+06 -8.203053e+00 -9.744031e+01
omega  -1.205634e+09 -1.234074e+06 -1.703962e+13 -5.515881e+08 -8.452220e+08
alpha1 -3.466862e+04 -8.203053e+00 -5.515881e+08 -3.611224e+04 -4.469020e+04
beta1  -9.149105e+04 -9.744031e+01 -8.452220e+08 -4.469020e+04 -6.270062e+04
shape  -9.970351e+02  8.557532e-02 -3.050363e+06 -1.832755e+02 -2.340762e+02
               shape
mu     -9.970351e+02
ar1     8.557532e-02
omega  -3.050363e+06
alpha1 -1.832755e+02
beta1  -2.340762e+02
shape  -2.547431e+00
attr(,"time")
Time difference of 0.06522632 secs

--- END OF TRACE ---


Time to Estimate Parameters:
 Time difference of 0.3765259 secs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(djia.g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~arma(1, 0) + garch(1, 1), data = djiar, cond.dist = "std") 

Mean and Variance Equation:
 data ~ arma(1, 0) + garch(1, 1)
&lt;environment: 0x55e07ac38830&gt;
 [data = djiar]

Conditional Distribution:
 std 

Coefficient(s):
         mu          ar1        omega       alpha1        beta1        shape  
 8.5854e-04  -5.5315e-02   1.6101e-06   1.2444e-01   8.7001e-01   5.9788e+00  

Std. Errors:
 based on Hessian 

Error Analysis:
         Estimate  Std. Error  t value Pr(&gt;|t|)    
mu      8.585e-04   1.470e-04    5.842 5.16e-09 ***
ar1    -5.532e-02   2.023e-02   -2.735 0.006238 ** 
omega   1.610e-06   4.459e-07    3.611 0.000305 ***
alpha1  1.244e-01   1.660e-02    7.496 6.55e-14 ***
beta1   8.700e-01   1.526e-02   57.022  &lt; 2e-16 ***
shape   5.979e+00   7.917e-01    7.552 4.31e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 8249.619    normalized:  3.27756 

Description:
 Mon Nov 18 14:09:36 2024 by user:  


Standardised Residuals Tests:
                                  Statistic    p-Value
 Jarque-Bera Test   R    Chi^2  310.0081692 0.00000000
 Shapiro-Wilk Test  R    W        0.9820293 0.00000000
 Ljung-Box Test     R    Q(10)   16.8224601 0.07838596
 Ljung-Box Test     R    Q(15)   26.4481303 0.03356806
 Ljung-Box Test     R    Q(20)   28.7109935 0.09360790
 Ljung-Box Test     R^2  Q(10)   15.3676143 0.11922299
 Ljung-Box Test     R^2  Q(15)   19.1365044 0.20761469
 Ljung-Box Test     R^2  Q(20)   22.9288237 0.29230296
 LM Arch Test       R    TR^2    15.0397685 0.23926882

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-6.550353 -6.536453 -6.550364 -6.545309 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(djia.g)  # View model diagnostic plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summary-of-results" class="level4" data-number="3.2.1.3">
<h4 data-number="3.2.1.3" class="anchored" data-anchor-id="summary-of-results"><span class="header-section-number">3.2.1.3</span> Summary of Results</h4>
<p>The AR(1) coefficient ((_1)) is -0.05531, indicating a slight negative autocorrelation in returns. The GARCH parameters (_1 = 0.1244) and (_1 = 0.8700) are both significant, suggesting the model captures the observed volatility clustering in DJIA returns effectively.</p>
</section>
<section id="residual-diagnostics-1" class="level4" data-number="3.2.1.4">
<h4 data-number="3.2.1.4" class="anchored" data-anchor-id="residual-diagnostics-1"><span class="header-section-number">3.2.1.4</span> Residual Diagnostics</h4>
<p>Residual diagnostics are as follows:</p>
<ul>
<li><strong>Ljung-Box Test</strong>:
<ul>
<li>Residuals ([R]): (Q(10) = 16.82) (p-value = 0.0786), suggesting no significant autocorrelation in residuals.</li>
<li>Squared Residuals ([R^2]): (Q(10) = 15.39) (p-value = 0.1184), indicating no remaining ARCH effects.</li>
</ul></li>
</ul>
<p>These tests confirm that the AR(1)-GARCH(1, 1) model adequately captures the conditional heteroskedasticity in the DJIA returns.</p>
</section>
<section id="garch-predictions-of-volatility" class="level4" data-number="3.2.1.5">
<h4 data-number="3.2.1.5" class="anchored" data-anchor-id="garch-predictions-of-volatility"><span class="header-section-number">3.2.1.5</span> GARCH Predictions of Volatility</h4>
<p>We explored GARCH predictions of volatility, particularly around the financial crisis of 2008. One-step-ahead predictions of volatility ((^2)) were plotted along with the observed data, as shown in Figure 5.6. This provides insight into how volatility predictions varied during a period of high market uncertainty.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming `djia` is already loaded with a 'Close' column for DJIA closing prices</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate daily returns of DJIA</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>djiar <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">log</span>(djia<span class="sc">$</span>Close))[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the AR(1)-GARCH(1,1) model with t-distributed errors</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>djia.g <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span> <span class="fu">arma</span>(<span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">garch</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">data =</span> djiar, <span class="at">cond.dist =</span> <span class="st">"std"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Series Initialization:
 ARMA Model:                arma
 Formula Mean:              ~ arma(1, 0)
 GARCH Model:               garch
 Formula Variance:          ~ garch(1, 1)
 ARMA Order:                1 0
 Max ARMA Order:            1
 GARCH Order:               1 1
 Max GARCH Order:           1
 Maximum Order:             1
 Conditional Dist:          std
 h.start:                   2
 llh.start:                 1
 Length of Series:          2517
 Recursion Init:            mci
 Series Scale:              0.01210097

Parameter Initialization:
 Initial Parameters:          $params
 Limits of Transformations:   $U, $V
 Which Parameters are Fixed?  $includes
 Parameter Matrix:
                     U           V      params includes
    mu     -0.15336279   0.1533628  0.01533395     TRUE
    ar1    -0.99999999   1.0000000 -0.10129752     TRUE
    omega   0.00000100 100.0000000  0.10000000     TRUE
    alpha1  0.00000001   1.0000000  0.10000000     TRUE
    gamma1 -0.99999999   1.0000000  0.10000000    FALSE
    beta1   0.00000001   1.0000000  0.80000000     TRUE
    delta   0.00000000   2.0000000  2.00000000    FALSE
    skew    0.10000000  10.0000000  1.00000000    FALSE
    shape   1.00000000  10.0000000  4.00000000     TRUE
 Index List of Parameters to be Optimized:
    mu    ar1  omega alpha1  beta1  shape 
     1      2      3      4      6      9 
 Persistence:                  0.9 


--- START OF TRACE ---
Selected Algorithm: nlminb 

R coded nlminb Solver: 

  0:     2966.5649: 0.0153339 -0.101298 0.100000 0.100000 0.800000  4.00000
  1:     2944.7772: 0.0153351 -0.0991717 0.0803850 0.105688 0.794226  3.99986
  2:     2910.9438: 0.0153425 -0.0864389 0.0198837 0.162520 0.809278  4.00053
  3:     2891.9985: 0.0153434 -0.0855696 0.0349997 0.168391 0.817707  4.00077
  4:     2882.6364: 0.0153798 -0.0489475 0.0211398 0.164588 0.840541  4.00286
  5:     2881.9301: 0.0153823 -0.0484838 0.0204238 0.166791 0.845394  4.00314
  6:     2881.5679: 0.0153882 -0.0491671 0.0164038 0.164251 0.847793  4.00365
  7:     2880.9558: 0.0153959 -0.0493820 0.0174436 0.161528 0.852261  4.00434
  8:     2880.6291: 0.0154049 -0.0492037 0.0154767 0.158055 0.855764  4.00516
  9:     2880.3565: 0.0154166 -0.0487266 0.0159444 0.154678 0.859712  4.00626
 10:     2880.1243: 0.0154339 -0.0478609 0.0146355 0.150737 0.862389  4.00794
 11:     2879.9530: 0.0154638 -0.0476576 0.0149075 0.147959 0.865388  4.01087
 12:     2879.8201: 0.0155048 -0.0483157 0.0138749 0.146453 0.866639  4.01497
 13:     2879.7180: 0.0155488 -0.0477882 0.0141937 0.145774 0.867564  4.01936
 14:     2879.4141: 0.0157808 -0.0423403 0.0141381 0.141896 0.868277  4.04243
 15:     2878.3878: 0.0174980 -0.0569546 0.00848860 0.140360 0.874674  4.21079
 16:     2878.2927: 0.0193492 -0.0502757 0.0142265 0.160178 0.862535  4.37200
 17:     2876.3368: 0.0203874 -0.0461078 0.0117835 0.167862 0.852926  4.44641
 18:     2874.7342: 0.0206459 -0.0555791 0.0130825 0.138689 0.869340  4.42804
 19:     2874.6724: 0.0206462 -0.0554532 0.0123098 0.138461 0.869109  4.42806
 20:     2874.6548: 0.0206553 -0.0553211 0.0125311 0.138489 0.869292  4.42857
 21:     2874.6394: 0.0206635 -0.0550129 0.0122399 0.138334 0.869389  4.42904
 22:     2874.6234: 0.0206727 -0.0548830 0.0124501 0.138349 0.869554  4.42956
 23:     2874.6091: 0.0206813 -0.0546059 0.0121936 0.138189 0.869619  4.43005
 24:     2874.5943: 0.0206905 -0.0544775 0.0123915 0.138195 0.869769  4.43057
 25:     2874.5807: 0.0206992 -0.0542217 0.0121569 0.138035 0.869816  4.43107
 26:     2874.5667: 0.0207085 -0.0540958 0.0123467 0.138034 0.869956  4.43160
 27:     2874.5537: 0.0207174 -0.0538569 0.0121278 0.137877 0.869991  4.43211
 28:     2874.5403: 0.0207267 -0.0537340 0.0123108 0.137872 0.870123  4.43264
 29:     2874.5278: 0.0207356 -0.0535096 0.0121041 0.137717 0.870149  4.43315
 30:     2874.5149: 0.0207450 -0.0533899 0.0122810 0.137709 0.870275  4.43368
 31:     2874.5028: 0.0207540 -0.0531784 0.0120844 0.137558 0.870296  4.43419
 32:     2874.4904: 0.0207635 -0.0530620 0.0122555 0.137548 0.870416  4.43473
 33:     2874.4787: 0.0207726 -0.0528620 0.0120673 0.137401 0.870433  4.43525
 34:     2874.4667: 0.0207820 -0.0527489 0.0122328 0.137390 0.870549  4.43578
 35:     2874.4553: 0.0207912 -0.0525594 0.0120521 0.137247 0.870562  4.43630
 36:     2874.4437: 0.0208007 -0.0524496 0.0122124 0.137235 0.870674  4.43684
 37:     2874.4326: 0.0208099 -0.0522698 0.0120383 0.137096 0.870686  4.43736
 38:     2874.4213: 0.0208194 -0.0521631 0.0121935 0.137083 0.870794  4.43789
 39:     2874.4105: 0.0208287 -0.0519922 0.0120255 0.136949 0.870804  4.43842
 40:     2874.3995: 0.0208383 -0.0518887 0.0121759 0.136934 0.870909  4.43895
 41:     2874.3889: 0.0208476 -0.0517261 0.0120134 0.136805 0.870917  4.43948
 42:     2874.3782: 0.0208572 -0.0516257 0.0121593 0.136790 0.871020  4.44002
 43:     2874.3679: 0.0208666 -0.0514707 0.0120019 0.136664 0.871027  4.44055
 44:     2874.3574: 0.0208762 -0.0513733 0.0121435 0.136649 0.871126  4.44108
 45:     2874.3474: 0.0208856 -0.0512255 0.0119909 0.136527 0.871132  4.44161
 46:     2874.3371: 0.0208952 -0.0511310 0.0121283 0.136511 0.871229  4.44215
 47:     2874.3273: 0.0209047 -0.0509898 0.0119802 0.136393 0.871235  4.44268
 48:     2874.3172: 0.0209144 -0.0508982 0.0121136 0.136378 0.871329  4.44321
 49:     2874.3076: 0.0209239 -0.0507633 0.0119698 0.136263 0.871333  4.44374
 50:     2874.2977: 0.0209336 -0.0506745 0.0120995 0.136247 0.871425  4.44428
 51:     2874.2883: 0.0209431 -0.0505454 0.0119597 0.136136 0.871429  4.44481
 52:     2874.2786: 0.0209528 -0.0504593 0.0120858 0.136120 0.871519  4.44535
 53:     2874.2693: 0.0209624 -0.0503357 0.0119499 0.136012 0.871522  4.44588
 54:     2874.2598: 0.0209721 -0.0502524 0.0120725 0.135996 0.871609  4.44641
 55:     2874.2507: 0.0209817 -0.0501339 0.0119403 0.135891 0.871612  4.44694
 56:     2874.2414: 0.0209915 -0.0500532 0.0120596 0.135875 0.871697  4.44748
 57:     2874.2324: 0.0210011 -0.0499396 0.0119308 0.135773 0.871700  4.44801
 58:     2867.2502: 0.0374784 -0.0465701 0.0140411 0.146417 0.849465  5.34102
 59:     2865.2784: 0.0416151 -0.0568642 0.0115908 0.133741 0.863377  5.47854
 60:     2864.2803: 0.0508382 -0.0551564 0.0133502 0.137240 0.863921  5.39588
 61:     2861.7759: 0.0711833 -0.0514599 0.0116358 0.126101 0.868871  5.59207
 62:     2861.6890: 0.0720867 -0.0568481 0.0103059 0.127155 0.870034  5.77185
 63:     2861.6323: 0.0712594 -0.0580540 0.0105727 0.123206 0.871658  5.89046
 64:     2861.6059: 0.0710100 -0.0558795 0.0112294 0.125022 0.869481  5.92682
 65:     2861.6004: 0.0709184 -0.0550834 0.0110167 0.124375 0.870072  5.96212
 66:     2861.6000: 0.0709561 -0.0553609 0.0109915 0.124443 0.870018  5.97670
 67:     2861.6000: 0.0709474 -0.0553160 0.0109949 0.124443 0.870016  5.97866
 68:     2861.6000: 0.0709478 -0.0553153 0.0109957 0.124445 0.870013  5.97877

Final Estimate of the Negative LLH:
 LLH:  -8249.619    norm LLH:  -3.27756 
           mu           ar1         omega        alpha1         beta1 
 8.585376e-04 -5.531526e-02  1.610146e-06  1.244449e-01  8.700127e-01 
        shape 
 5.978770e+00 

R-optimhess Difference Approximated Hessian Matrix:
                  mu           ar1         omega        alpha1         beta1
mu     -4.791651e+07 -4.661861e+04 -1.205634e+09 -3.466862e+04 -9.149105e+04
ar1    -4.661861e+04 -2.490882e+03 -1.234074e+06 -8.203053e+00 -9.744031e+01
omega  -1.205634e+09 -1.234074e+06 -1.703962e+13 -5.515881e+08 -8.452220e+08
alpha1 -3.466862e+04 -8.203053e+00 -5.515881e+08 -3.611224e+04 -4.469020e+04
beta1  -9.149105e+04 -9.744031e+01 -8.452220e+08 -4.469020e+04 -6.270062e+04
shape  -9.970351e+02  8.557532e-02 -3.050363e+06 -1.832755e+02 -2.340762e+02
               shape
mu     -9.970351e+02
ar1     8.557532e-02
omega  -3.050363e+06
alpha1 -1.832755e+02
beta1  -2.340762e+02
shape  -2.547431e+00
attr(,"time")
Time difference of 0.06753659 secs

--- END OF TRACE ---


Time to Estimate Parameters:
 Time difference of 0.3646638 secs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract fitted volatility (sigma) from the GARCH model</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>predicted_volatility <span class="ot">&lt;-</span> djia.g<span class="sc">@</span>sigma.t</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up a time series index (assuming `djiar` has time index matching `predicted_volatility`)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">index</span>(djiar)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the observed returns and predicted volatility</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dates, djiar, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">ylab =</span> <span class="st">"Returns and Volatility"</span>, <span class="at">xlab =</span> <span class="st">"Date"</span>, <span class="at">main =</span> <span class="st">"DJIA Returns and GARCH(1,1) Predicted Volatility"</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(dates, predicted_volatility, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a legend</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Observed Returns"</span>, <span class="st">"Predicted Volatility (GARCH)"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap5_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="aparch-analysis-of-the-djia-returns" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="aparch-analysis-of-the-djia-returns"><span class="header-section-number">3.3</span> APARCH Analysis of the DJIA Returns</h2>
<section id="background-2" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="background-2"><span class="header-section-number">3.3.1</span> Background</h3>
<p>In this example, we apply an AR-APARCH model to the DJIA returns, as discussed in Example 5.5. Similar to the previous example, an AR(1) term is included in the model to account for the conditional mean. We assume that the error process follows an APARCH(1,1) structure with t-distributed errors to capture asymmetry and heavy tails in the return series. The model equation is:</p>
<p>[ r_t = _t + y_t ]</p>
<p>where ( _t ) is an AR(1) component, and ( y_t ) follows an APARCH process with conditional variance modeled as specified in Equation (5.53).</p>
<section id="model-fitting-and-summary" class="level4" data-number="3.3.1.1">
<h4 data-number="3.3.1.1" class="anchored" data-anchor-id="model-fitting-and-summary"><span class="header-section-number">3.3.1.1</span> Model Fitting and Summary</h4>
<p>We use the <code>fGarch</code> package in R to fit the AR-APARCH(1,1) model to the DJIA returns. The following code performs the fitting and provides a summary of the estimated parameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xts)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fGarch)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate daily returns of DJIA</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>djiar <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">log</span>(djia<span class="sc">$</span>Close))[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit AR(1)-APARCH(1,1) model with t-distributed errors</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>djia.ap <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span> <span class="fu">arma</span>(<span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">aparch</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">data =</span> djiar, <span class="at">cond.dist =</span> <span class="st">"std"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Series Initialization:
 ARMA Model:                arma
 Formula Mean:              ~ arma(1, 0)
 GARCH Model:               aparch
 Formula Variance:          ~ aparch(1, 1)
 ARMA Order:                1 0
 Max ARMA Order:            1
 GARCH Order:               1 1
 Max GARCH Order:           1
 Maximum Order:             1
 Conditional Dist:          std
 h.start:                   2
 llh.start:                 1
 Length of Series:          2517
 Recursion Init:            mci
 Series Scale:              0.01210097

Parameter Initialization:
 Initial Parameters:          $params
 Limits of Transformations:   $U, $V
 Which Parameters are Fixed?  $includes
 Parameter Matrix:
                     U           V      params includes
    mu     -0.15336279   0.1533628  0.01533395     TRUE
    ar1    -0.99999999   1.0000000 -0.10129752     TRUE
    omega   0.00000100 100.0000000  0.10000000     TRUE
    alpha1  0.00000001   1.0000000  0.10000000     TRUE
    gamma1 -0.99999999   1.0000000  0.10000000     TRUE
    beta1   0.00000001   1.0000000  0.80000000     TRUE
    delta   0.00000000   2.0000000  2.00000000     TRUE
    skew    0.10000000  10.0000000  1.00000000    FALSE
    shape   1.00000000  10.0000000  4.00000000     TRUE
 Index List of Parameters to be Optimized:
    mu    ar1  omega alpha1 gamma1  beta1  delta  shape 
     1      2      3      4      5      6      7      9 
 Persistence:                  0.901 


--- START OF TRACE ---
Selected Algorithm: nlminb 

R coded nlminb Solver: 

  0:     2956.2216: 0.0153339 -0.101298 0.100000 0.100000 0.100000 0.800000  2.00000  4.00000
  1:     2933.7103: 0.0153349 -0.0994952 0.0816702 0.105086 0.101441 0.794372  1.99989  3.99987
  2:     2915.7667: 0.0153364 -0.0969033 0.0659019 0.116672 0.103734 0.795785  2.00000  3.99997
  3:     2868.4755: 0.0153445 -0.0848310 0.0240071 0.174769 0.115713 0.826263  2.00000  4.00127
  4:     2866.0067: 0.0153484 -0.0806140 0.0223751 0.179103 0.121376 0.835430  2.00000  4.00180
  5:     2865.7487: 0.0153525 -0.0768014 0.0131222 0.176106 0.127212 0.838921  1.99992  4.00228
  6:     2863.1420: 0.0153538 -0.0756613 0.0180358 0.176968 0.129016 0.841888  2.00000  4.00245
  7:     2856.2449: 0.0153875 -0.0476167 0.00965957 0.170079 0.175758 0.860641  1.99995  4.00607
  8:     2853.4108: 0.0154249 -0.0295659 0.0252436 0.165440 0.224654 0.839180  1.99938  4.00936
  9:     2853.0448: 0.0154257 -0.0299884 0.0155240 0.163926 0.225784 0.836602  1.99923  4.00941
 10:     2850.4568: 0.0154262 -0.0301237 0.0197886 0.165257 0.226344 0.839033  1.99934  4.00951
 11:     2849.7888: 0.0154284 -0.0309518 0.0166941 0.166172 0.229095 0.841761  1.99938  4.00981
 12:     2849.3808: 0.0154318 -0.0322155 0.0188338 0.167018 0.233146 0.843406  1.99940  4.01023
 13:     2848.6297: 0.0154356 -0.0334350 0.0170783 0.166875 0.237702 0.842613  1.99931  4.01065
 14:     2848.2726: 0.0154392 -0.0343915 0.0177679 0.167228 0.241904 0.845217  1.99934  4.01111
 15:     2847.6118: 0.0154433 -0.0353050 0.0161095 0.167003 0.246509 0.844166  1.99923  4.01155
 16:     2839.6580: 0.0155653 -0.0553493 0.0222431 0.178380 0.380319 0.824116  1.99673  4.02506
 17:     2839.3512: 0.0155658 -0.0550968 0.0204751 0.177743 0.380646 0.823994  1.99667  4.02511
 18:     2838.9545: 0.0155699 -0.0530330 0.0209096 0.175844 0.383429 0.828959  1.99653  4.02564
 19:     2838.4453: 0.0155822 -0.0490947 0.0190161 0.175891 0.387313 0.827244  1.99538  4.02695
 20:     2838.2004: 0.0155983 -0.0451962 0.0202650 0.176410 0.391417 0.827097  1.99373  4.02871
 21:     2837.9655: 0.0156258 -0.0427583 0.0191101 0.176071 0.394484 0.826442  1.99035  4.03170
 22:     2837.7164: 0.0156586 -0.0433600 0.0199725 0.175167 0.395086 0.827962  1.98601  4.03528
 23:     2837.4877: 0.0156899 -0.0444502 0.0188067 0.173444 0.395339 0.829067  1.98177  4.03873
 24:     2837.2542: 0.0157227 -0.0444858 0.0196845 0.172775 0.396371 0.830254  1.97741  4.04241
 25:     2837.0243: 0.0157544 -0.0436348 0.0187730 0.171889 0.398204 0.830412  1.97322  4.04605
 26:     2836.8012: 0.0157867 -0.0431291 0.0196235 0.171422 0.399701 0.831316  1.96895  4.04979
 27:     2836.5848: 0.0158187 -0.0432528 0.0186828 0.170271 0.400698 0.831832  1.96461  4.05354
 28:     2836.3739: 0.0158508 -0.0434055 0.0194501 0.169589 0.401625 0.832972  1.96028  4.05734
 29:     2836.1649: 0.0158827 -0.0431931 0.0185802 0.168628 0.402869 0.833293  1.95598  4.06117
 30:     2835.9597: 0.0159145 -0.0428368 0.0193553 0.168170 0.404207 0.834156  1.95172  4.06504
 31:     2835.7585: 0.0159462 -0.0426654 0.0185188 0.167252 0.405404 0.834462  1.94744  4.06892
 32:     2835.5621: 0.0159779 -0.0426467 0.0192452 0.166709 0.406444 0.835427  1.94316  4.07284
 33:     2835.3683: 0.0160095 -0.0425704 0.0184359 0.165808 0.407541 0.835744  1.93888  4.07678
 34:     2835.1779: 0.0160411 -0.0423779 0.0191523 0.165365 0.408710 0.836588  1.93464  4.08076
 35:     2834.9901: 0.0160726 -0.0421938 0.0183829 0.164555 0.409882 0.836832  1.93040  4.08474
 36:     2834.8061: 0.0161042 -0.0420878 0.0190714 0.164114 0.410966 0.837674  1.92617  4.08876
 37:     2834.6246: 0.0161357 -0.0420095 0.0183222 0.163312 0.412035 0.837939  1.92194  4.09279
 38:     2834.4462: 0.0161673 -0.0418854 0.0189920 0.162910 0.413121 0.838736  1.91773  4.09685
 39:     2834.2698: 0.0161987 -0.0417390 0.0182750 0.162177 0.414233 0.838949  1.91352  4.10092
 40:     2834.0965: 0.0162303 -0.0416151 0.0189257 0.161805 0.415308 0.839711  1.90934  4.10501
 41:     2833.9253: 0.0162618 -0.0415237 0.0182290 0.161092 0.416362 0.839927  1.90514  4.10911
 42:     2833.7569: 0.0162934 -0.0414219 0.0188604 0.160741 0.417408 0.840667  1.90097  4.11324
 43:     2833.5901: 0.0163250 -0.0413048 0.0181889 0.160075 0.418472 0.840852  1.89680  4.11737
 44:     2833.4261: 0.0163566 -0.0411882 0.0188048 0.159756 0.419520 0.841555  1.89265  4.12152
 45:     2833.2636: 0.0163883 -0.0410937 0.0181531 0.159117 0.420555 0.841733  1.88849  4.12568
 46:     2833.1037: 0.0164201 -0.0410006 0.0187518 0.158815 0.421575 0.842418  1.88435  4.12986
 47:     2832.9452: 0.0164519 -0.0409017 0.0181207 0.158211 0.422604 0.842576  1.88021  4.13404
 48:     2832.7890: 0.0164838 -0.0407973 0.0187056 0.157937 0.423625 0.843229  1.87609  4.13824
 49:     2832.6341: 0.0165157 -0.0407067 0.0180929 0.157360 0.424638 0.843376  1.87196  4.14245
 50:     2832.4815: 0.0165478 -0.0406213 0.0186628 0.157101 0.425636 0.844012  1.86786  4.14667
 51:     2832.3300: 0.0165799 -0.0405346 0.0180677 0.156553 0.426639 0.844146  1.86374  4.15089
 52:     2832.1806: 0.0166122 -0.0404422 0.0186253 0.156317 0.427635 0.844755  1.85965  4.15513
 53:     2832.0323: 0.0166446 -0.0403594 0.0180468 0.155794 0.428627 0.844877  1.85556  4.15937
 54:     2831.8860: 0.0166771 -0.0402797 0.0185914 0.155574 0.429607 0.845469  1.85148  4.16362
 55:     2831.7406: 0.0167096 -0.0402025 0.0180284 0.155074 0.430588 0.845580  1.84740  4.16787
 56:     2831.5971: 0.0167424 -0.0401200 0.0185619 0.154873 0.431564 0.846150  1.84334  4.17214
 57:     2823.2275: 0.0241723 -0.0178143 0.0279421 0.154694 0.570032 0.852884 0.917653  5.13851
 58:     2823.0077: 0.0243118 -0.0209096 0.0315367 0.155146 0.569922 0.857579 0.900545  5.15526
 59:     2820.5079: 0.0243219 -0.0208801 0.0294576 0.153786 0.569402 0.856246 0.913322  5.15707
 60:     2820.0209: 0.0243261 -0.0259732 0.0222170 0.153394 0.574190 0.864662 0.914968  5.15741
 61:     2819.2340: 0.0243310 -0.0260678 0.0232473 0.153113 0.573853 0.865714 0.928086  5.15821
 62:     2814.8421: 0.0250357 -0.0398787 0.0179842 0.132129 0.560768 0.879198  1.17994  5.25066
 63:     2814.8331: 0.0254014 -0.0459558 0.0176973 0.127988 0.560005 0.881149  1.15004  5.28917
 64:     2814.4735: 0.0257755 -0.0467011 0.0185883 0.127078 0.563492 0.882539  1.14177  5.29761
 65:     2814.2272: 0.0257944 -0.0428649 0.0182816 0.128524 0.566955 0.880937  1.15745  5.27588
 66:     2813.7698: 0.0261858 -0.0419618 0.0205550 0.126865 0.575104 0.878813  1.16041  5.27253
 67:     2813.4645: 0.0265757 -0.0420537 0.0199896 0.126314 0.578671 0.878986  1.15776  5.28170
 68:     2812.8046: 0.0272480 -0.0320793 0.0193600 0.130919 0.591671 0.876133  1.19909  5.24647
 69:     2807.7324: 0.0427119 -0.0513132 0.0210760 0.111811 0.708844 0.891478  1.07619  5.77275
 70:     2801.4712: 0.0560713 -0.0740097 0.0208609 0.114749 0.814103 0.879998  1.09695  6.51607
 71:     2800.2814: 0.0553548 -0.0644686 0.0202525 0.107577 0.852183 0.886684  1.07015  6.48728
 72:     2799.8245: 0.0532178 -0.0594050 0.0214275 0.105320 0.890711 0.889987  1.07690  6.46536
 73:     2798.3999: 0.0510334 -0.0569062 0.0207359 0.103398 0.923747 0.890912  1.06938  6.47024
 74:     2796.9941: 0.0438258 -0.0476311 0.0199962 0.0978223  1.00000 0.895386  1.07274  6.73868
 75:     2796.8730: 0.0433183 -0.0483913 0.0202190 0.0982598  1.00000 0.894017  1.07497  7.09290
 76:     2796.8639: 0.0434729 -0.0476753 0.0199892 0.0976425  1.00000 0.893818  1.09162  7.27643
 77:     2796.8505: 0.0433533 -0.0483650 0.0202096 0.0977215  1.00000 0.894083  1.07973  7.27834
 78:     2796.8484: 0.0433224 -0.0483607 0.0202113 0.0980776  1.00000 0.894201  1.07448  7.26945
 79:     2796.8473: 0.0432669 -0.0482305 0.0202565 0.0981140  1.00000 0.894400  1.07069  7.27836
 80:     2796.8472: 0.0432528 -0.0481818 0.0202574 0.0980857  1.00000 0.894466  1.07018  7.28534
 81:     2796.8472: 0.0432523 -0.0481871 0.0202604 0.0980913  1.00000 0.894455  1.07022  7.28569
 82:     2796.8472: 0.0432531 -0.0481833 0.0202594 0.0980894  1.00000 0.894456  1.07024  7.28577

Final Estimate of the Negative LLH:
 LLH:  -8311.583    norm LLH:  -3.302178 
           mu           ar1         omega        alpha1        gamma1 
 0.0005234050 -0.0481832641  0.0001798009  0.0980893747  0.9999999900 
        beta1         delta         shape 
 0.8944563711  1.0702355865  7.2857704887 

R-optimhess Difference Approximated Hessian Matrix:
                  mu           ar1         omega        alpha1        gamma1
mu      -92572375.49 -1.304310e+05 -6.613022e+08 -2.435867e+06 -1.277035e+05
ar1       -130430.97 -2.960609e+03 -7.708017e+05 -1.492684e+03 -7.809006e+01
omega  -661302169.81 -7.708017e+05 -9.933158e+09 -3.284973e+07 -1.721832e+06
alpha1   -2435867.05 -1.492684e+03 -3.284973e+07 -1.662171e+05 -8.715935e+03
gamma1    -127703.52 -7.809006e+01 -1.721832e+06 -8.715935e+03 -9.620990e+03
beta1    -3642690.42 -3.791544e+03 -5.191605e+07 -2.185958e+05 -1.146447e+04
delta     -248101.20 -2.643135e+02 -3.568338e+06 -1.497208e+04 -7.831015e+02
shape       -4448.78 -2.850922e+00 -4.321048e+04 -2.197835e+02 -1.153887e+01
               beta1         delta         shape
mu      -3642690.416 -2.481012e+05  -4448.780252
ar1        -3791.544 -2.643135e+02     -2.850922
omega  -51916048.337 -3.568338e+06 -43210.482623
alpha1   -218595.807 -1.497208e+04   -219.783489
gamma1    -11464.468 -7.831015e+02    -11.538865
beta1    -320129.731 -2.153576e+04   -285.455040
delta     -21535.759 -1.520674e+03    -19.343988
shape       -285.455 -1.934399e+01     -1.118540
attr(,"time")
Time difference of 0.1159267 secs

--- END OF TRACE ---


Time to Estimate Parameters:
 Time difference of 0.5305257 secs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(djia.ap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~arma(1, 0) + aparch(1, 1), data = djiar, 
    cond.dist = "std") 

Mean and Variance Equation:
 data ~ arma(1, 0) + aparch(1, 1)
&lt;environment: 0x55e079d0bff0&gt;
 [data = djiar]

Conditional Distribution:
 std 

Coefficient(s):
        mu         ar1       omega      alpha1      gamma1       beta1  
 0.0005234  -0.0481833   0.0001798   0.0980894   1.0000000   0.8944564  
     delta       shape  
 1.0702356   7.2857705  

Std. Errors:
 based on Hessian 

Error Analysis:
         Estimate  Std. Error  t value Pr(&gt;|t|)    
mu      5.234e-04   1.525e-04    3.433 0.000598 ***
ar1    -4.818e-02   1.934e-02   -2.491 0.012729 *  
omega   1.798e-04   3.443e-05    5.222 1.77e-07 ***
alpha1  9.809e-02   1.030e-02    9.525  &lt; 2e-16 ***
gamma1  1.000e+00   1.045e-02   95.728  &lt; 2e-16 ***
beta1   8.945e-01   1.049e-02   85.279  &lt; 2e-16 ***
delta   1.070e+00   1.350e-01    7.928 2.22e-15 ***
shape   7.286e+00   1.123e+00    6.490 8.61e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 8311.583    normalized:  3.302178 

Description:
 Mon Nov 18 14:09:37 2024 by user:  


Standardised Residuals Tests:
                                 Statistic     p-Value
 Jarque-Bera Test   R    Chi^2  245.156078 0.000000000
 Shapiro-Wilk Test  R    W        0.983058 0.000000000
 Ljung-Box Test     R    Q(10)   15.595870 0.111800290
 Ljung-Box Test     R    Q(15)   26.450980 0.033541324
 Ljung-Box Test     R    Q(20)   30.170758 0.067133620
 Ljung-Box Test     R^2  Q(10)   19.176843 0.038073151
 Ljung-Box Test     R^2  Q(15)   30.466591 0.010345882
 Ljung-Box Test     R^2  Q(20)   35.364460 0.018246902
 LM Arch Test       R    TR^2    29.577276 0.003231735

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-6.598000 -6.579468 -6.598020 -6.591274 </code></pre>
</div>
</div>
</section>
<section id="parameter-estimates" class="level4" data-number="3.3.1.2">
<h4 data-number="3.3.1.2" class="anchored" data-anchor-id="parameter-estimates"><span class="header-section-number">3.3.1.2</span> Parameter Estimates</h4>
<p>The AR(1) coefficient (_1) is -0.04818, while the APARCH parameters (_1), (_1), and () indicate the model captures asymmetry and persistence in volatility.</p>
</section>
<section id="residual-diagnostics-2" class="level4" data-number="3.3.1.3">
<h4 data-number="3.3.1.3" class="anchored" data-anchor-id="residual-diagnostics-2"><span class="header-section-number">3.3.1.3</span> Residual Diagnostics</h4>
<p>Several tests were performed to check the residuals for independence and normality:</p>
<ul>
<li><strong>Ljung-Box Test</strong>:
<ul>
<li>Residuals ([R]): (Q(10) = 15.71), with a p-value of 0.108, suggesting no significant autocorrelation in the residuals.</li>
<li>Squared Residuals ([R^2]): (Q(10) = 16.87), with a p-value of 0.077, indicating no remaining ARCH effects.</li>
</ul></li>
</ul>
</section>
<section id="predicted-volatility" class="level4" data-number="3.3.1.4">
<h4 data-number="3.3.1.4" class="anchored" data-anchor-id="predicted-volatility"><span class="header-section-number">3.3.1.4</span> Predicted Volatility</h4>
<p>The predicted volatility from the APARCH model differs from the GARCH model but displays similar volatility clustering patterns. To compare, we plot the observed returns and the one-step-ahead predicted volatility.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot observed returns and APARCH predicted volatility</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">index</span>(djiar)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>predicted_volatility_aparch <span class="ot">&lt;-</span> djia.ap<span class="sc">@</span>sigma.t</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dates, djiar, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">ylab =</span> <span class="st">"Returns and Volatility"</span>, <span class="at">xlab =</span> <span class="st">"Date"</span>, <span class="at">main =</span> <span class="st">"DJIA Returns and APARCH(1,1) Predicted Volatility"</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(dates, predicted_volatility_aparch, <span class="at">col =</span> <span class="st">"green"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a legend</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Observed Returns"</span>, <span class="st">"Predicted Volatility (APARCH)"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"green"</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap5_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot compares the daily returns with the APARCH model’s predicted volatility, highlighting volatility clustering in the DJIA returns over time.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./cap4.html" class="pagination-link" aria-label="Capítulo 4">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Capítulo 4</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>